sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake --version
  - source /opt/qt55/bin/qt55-env.sh
  - qmake -v
  - cmake .. && make
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
install:
  - sudo apt-get -y install qt55tools qt55script qt55base
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - g++-5
      - clang-3.7


