sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - cmake --version
  - qmake -v
  - cmake .. && make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - sourceline: 'ppa:beineri/opt-qt532-trusty'
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - g++-5
      - clang-3.7
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qt5-qmake
      - qttools5-dev-tools


